version: "3"

services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'database'
      TZ: "Asia/Tokyo"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
